/**
 * Canonical CSV → HubSpot property mapping. Single source of truth.
 *
 * Generated by inspection of the live HubSpot schema (see schemas/*.json).
 * If HubSpot schema changes, re-pull and update this file.
 *
 * Structure for each entry:
 *   csv:      CSV header name as it appears in the file
 *   prop:     HubSpot property name (snake_case, matches schema exactly)
 *   type:     HubSpot property type
 *             'string' | 'number' | 'bool' | 'date' | 'enumeration'
 *   coerce:   (optional) explicitly authorize a transformation at send time.
 *             'date_only'    → strip time portion; raw datetime preserved in raw_csv
 *             'email_strict' → validate RFC-ish; suspect rows isolated in 1-row batches
 *             'zip_format'   → reshape a 9-digit ZIP to ZIP+4 (448705016 → 44870-5016)
 *             'yn_to_bool'   → Y/N string → boolean
 *             undefined      → DEFAULT. No coercion. Send the trimmed raw value as-is.
 *                              If HubSpot rejects, the rejection surfaces per record loudly.
 *
 * Per memory financial_data_rules.md (Rule 3): coercions require explicit opt-in.
 * Default behavior is to send raw and let HubSpot reject mismatches. Every coercion
 * is recorded as an audit row in the staging row's `coercions` JSONB column.
 *
 * Fields with no HubSpot target are intentionally omitted (dropped at parse,
 * but preserved verbatim in raw_csv on the staging row).
 */

// CIF CSV → Contact or Company, depending on classification.
// Only truly-common fields go here. Verified against HubSpot schemas/contacts.json
// and schemas/companies.json.
const CIF_COMMON = [
  { csv: 'CIFNum',              prop: 'cif_number',                              type: 'string' },
  { csv: 'Email',               prop: 'email',                                   type: 'string', coerce: 'email_strict' },
  { csv: 'PhoneNumber',         prop: 'phone',                                   type: 'string' },
  { csv: 'Address1',            prop: 'address',                                 type: 'string' },
  { csv: 'City',                prop: 'city',                                    type: 'string' },
  { csv: 'State',               prop: 'state',                                   type: 'string' },
  { csv: 'ZipCode',             prop: 'zip',                                     type: 'string', coerce: 'zip_format' },
  { csv: 'HashSSN',             prop: 'hashed_ssn',                              type: 'string' },
  { csv: 'DoNotCall',           prop: 'dnc_flag_yn',                             type: 'bool', coerce: 'yn_to_bool' },
  { csv: 'InsiderCode',         prop: 'insider_code',                            type: 'string' },
  { csv: 'InsufficientAddress', prop: 'insufficient_address_yn',                 type: 'bool', coerce: 'yn_to_bool' },
  { csv: 'CLFFlag',             prop: 'clf_flag_yn',                             type: 'bool', coerce: 'yn_to_bool' },
  { csv: 'CivAtWork',           prop: 'civistawork_yn',                          type: 'bool', coerce: 'yn_to_bool' },
  { csv: 'OrigCustDate',        prop: 'orginal_customer_date',                   type: 'date', coerce: 'date_only' },   // HubSpot typo preserved
  // Deceased: source convention uses ' ' (space) for alive, 'Y' for deceased.
  // Special-cased in buildPayload (NOT yn_to_bool) because " "/"N"/empty all → false.
  { csv: 'Deceased',            prop: 'deceased_flag_yn',                        type: 'bool' },
  { csv: 'ClassCode',           prop: 'class_code',                              type: 'string' },
  { csv: 'TaxIdType',           prop: 'tax_id_type',                             type: 'enumeration' },
  { csv: 'CustRelNum',          prop: 'customer_relationship_number',            type: 'string' },
  { csv: 'DigBank',             prop: 'digital_banking_flag_yn',                 type: 'bool', coerce: 'yn_to_bool' },
  { csv: 'ATMDebitCard',        prop: 'atmdebit_card_yn',                        type: 'bool', coerce: 'yn_to_bool' },
  { csv: 'Q2userID',            prop: 'q2_user_id',                              type: 'string' },
  { csv: 'LastLogin',           prop: 'last_login',                              type: 'date', coerce: 'date_only' },
  { csv: 'RecurTrans',          prop: 'recurring_transactions_yn',               type: 'bool', coerce: 'yn_to_bool' },
  { csv: 'StmtType',            prop: 'stmt_type',                               type: 'enumeration' },
  { csv: 'EnrollmentDt',        prop: 'enrollment_date',                         type: 'date', coerce: 'date_only' },
  { csv: 'CentralGroupID',      prop: 'central_group_id',                        type: 'string' },
  { csv: 'TextOptIn',           prop: 'text_opt_in',                             type: 'bool', coerce: 'yn_to_bool' },
  { csv: 'DiscAcpt',            prop: 'estatement_disclosure_acceptance_date',   type: 'bool', coerce: 'yn_to_bool' },
];

// Contact-only properties (don't exist on HubSpot companies).
const CIF_CONTACT_ONLY = [
  { csv: 'FirstName',   prop: 'firstname',                  type: 'string' },
  { csv: 'LastName',    prop: 'lastname',                   type: 'string' },
  { csv: 'Birthday',    prop: 'date_of_birth',              type: 'date', coerce: 'date_only' },
  { csv: 'Address2',    prop: 'street_address_2',           type: 'string' },
  { csv: 'PrivBanking', prop: 'private_banking_flag_yn',    type: 'bool', coerce: 'yn_to_bool' },
  { csv: 'Minor',       prop: 'minor_flag_yn',              type: 'bool', coerce: 'yn_to_bool' },
];

// Company-only properties (don't exist on HubSpot contacts).
const CIF_COMPANY_ONLY = [
  { csv: 'FullName',  prop: 'name',                          type: 'string' },
  { csv: 'NAICSCode', prop: 'naics_code',                    type: 'string' },
  { csv: 'TM',        prop: 'treasury_management_flag_yn',   type: 'bool', coerce: 'yn_to_bool' },
];

const CIF_CONTACT_FIELDS = [...CIF_COMMON, ...CIF_CONTACT_ONLY];
const CIF_COMPANY_FIELDS = [...CIF_COMMON, ...CIF_COMPANY_ONLY];

// DDA CSV → Deposits (custom object 2-60442978).
const DDA_FIELDS = [
  // account_key is the account-level upsert identity (one HubSpot record per
  // physical account; see ACCOUNT_KEY_COLUMNS / buildAccountKey). It is NOT a
  // CSV column — it's derived during parse — so it carries no `csv` source.
  { csv: null,            prop: 'account_key',              type: 'string', derived: true },
  { csv: 'PrimaryKey',    prop: 'primary_key',              type: 'string' },
  { csv: 'Acctlast4',     prop: 'last_4_account_digits',    type: 'string' },
  { csv: 'CIF#',          prop: 'cif_number',               type: 'string' },
  { csv: 'InterestRate',  prop: 'interest_rate',            type: 'number' },
  { csv: 'accttype',      prop: 'account_type',             type: 'enumeration' },
  { csv: 'acctdesc',      prop: 'account_description',      type: 'string' },
  { csv: 'opendate',      prop: 'date_opened',              type: 'date' },
  { csv: 'closedate',     prop: 'date_closed',              type: 'date' },
  { csv: 'slsassoc',      prop: 'sales_associate',          type: 'string' },
  { csv: 'dtlastactive',  prop: 'date_last_active',         type: 'date' },
  { csv: 'currentbal',    prop: 'current_balance',          type: 'number' },
  { csv: 'yestbal',       prop: 'yesterdays_balance',       type: 'number' },
  { csv: 'branchnum',     prop: 'branch_number',            type: 'string' },
  { csv: 'officrcode',    prop: 'officer_name',             type: 'string' },
  { csv: 'acctstatus',    prop: 'deposit_account_status',   type: 'enumeration' },
  { csv: 'promocode',     prop: 'promo_code',               type: 'string' },
  { csv: 'openonline',    prop: 'opened_online_yn',         type: 'bool', coerce: 'yn_to_bool' },
  // per-owner `relationship` MUST stay in the mapping so the parser captures
  // it (owner-table labels + canonical primary-owner selection depend on
  // mapped.relationship), but `send: false` keeps it OFF the account payload.
  // Under the Option B dedup model one account has many owners each with their
  // own relationship — that belongs on the labeled owner associations
  // (relationship-map.js), not as a single ambiguous enum on the account.
  // (HubSpot's account picklist also only allowed P/C/M/B/X, so real codes
  // like W/D would 400 the whole batch.)
  { csv: 'relationship',  prop: 'relationship',             type: 'enumeration', send: false },
];

// Loans CSV → Loans (custom object 2-60442977).
const LOANS_FIELDS = [
  { csv: null,              prop: 'account_key',            type: 'string', derived: true },
  { csv: 'PrimaryKey',      prop: 'primary_key',            type: 'string' },
  { csv: 'acctlast4',       prop: 'last_4_account_digits',  type: 'string' },
  { csv: 'CIFNum',          prop: 'cif_number',             type: 'string' },
  { csv: 'InterestRate',    prop: 'interest_rate',          type: 'number' },
  { csv: 'accttype',        prop: 'account_type',           type: 'enumeration' },
  { csv: 'loantype',        prop: 'loan_type',              type: 'enumeration' },
  { csv: 'origdate',        prop: 'orgination_date',        type: 'date' },   // HubSpot typo, preserved
  { csv: 'maturitydate',    prop: 'maturity_date',          type: 'date' },
  { csv: 'slsassoc',        prop: 'sales_associate',        type: 'string' },
  { csv: 'lastactivedate',  prop: 'date_last_active',       type: 'date' },
  { csv: 'currbal',         prop: 'current_balance',        type: 'number' },
  { csv: 'branchnum',       prop: 'branch_number',          type: 'string' },
  { csv: 'officrcode',      prop: 'officer_name',           type: 'string' },
  { csv: 'acctstatus',      prop: 'loan_status',            type: 'enumeration' },
  { csv: 'origbal',         prop: 'original_balance',       type: 'number' },
  // captured for owner associations / primary-owner selection; not sent to HubSpot (see DDA note)
  { csv: 'relationship',    prop: 'relationship',           type: 'enumeration', send: false },
];

// CD CSV → Time Deposits (custom object 2-60442980).
const CD_FIELDS = [
  { csv: null,            prop: 'account_key',              type: 'string', derived: true },
  { csv: 'PrimaryKey',    prop: 'primary_key',              type: 'string' },
  { csv: 'AcctLast4',     prop: 'last_4_account_digits',    type: 'string' },
  { csv: 'CIFNum',        prop: 'cif_number',               type: 'string' },
  { csv: 'InterestRate',  prop: 'interest_rate',            type: 'number' },
  { csv: 'accttype',      prop: 'account_type',             type: 'enumeration' },
  { csv: 'acctdesc',      prop: 'account_description',      type: 'string' },
  { csv: 'issuedate',     prop: 'issue_date',               type: 'date' },
  { csv: 'maturitydate',  prop: 'maturity_date',            type: 'date' },
  { csv: 'slsassoc',      prop: 'sales_associate',          type: 'string' },
  { csv: 'currbal',       prop: 'current_balance',          type: 'number' },
  { csv: 'branchnum',     prop: 'branch_number',            type: 'string' },
  { csv: 'officrcode',    prop: 'officer_name',             type: 'string' },
  { csv: 'acctstatus',    prop: 'time_deposit_status',      type: 'enumeration' },
  { csv: 'openonline',    prop: 'opened_online_yn',         type: 'bool', coerce: 'yn_to_bool' },
  // captured for owner associations / primary-owner selection; not sent to HubSpot (see DDA note)
  { csv: 'relationship',  prop: 'relationship',             type: 'enumeration', send: false },
];

// Debit Card CSV → Debit Cards (custom object 2-60442979).
const DEBIT_CARDS_FIELDS = [
  { csv: 'CIF#',             prop: 'cif_number',                       type: 'string' },
  { csv: 'Acctlast4',        prop: 'last_4_of_associated_account',     type: 'string' },
  { csv: 'AcctType',         prop: 'associated_account_type',          type: 'enumeration' },
  { csv: 'Last4DebitCard',   prop: 'last_4_of_debit_card_digits',      type: 'string' },
  { csv: 'CardStatus',       prop: 'card_status',                      type: 'enumeration' },
  { csv: 'Expiredate',       prop: 'expiration_date',                  type: 'date' },
  { csv: 'Lastuseddt',       prop: 'last_used',                        type: 'date' },
  { csv: 'POSLast30Days',    prop: 'pos_trans_count__last_30_day',     type: 'number' },
  { csv: 'ActivePOS',        prop: 'active_pos',                       type: 'bool', coerce: 'yn_to_bool' },
  // composite_key is generated (not in CSV) — handled specially in parser.
];

/**
 * Account-level grouping key.
 *
 * In the Silver Lake source files a single physical account appears as one row
 * per owner — each row carrying its own per-owner `PrimaryKey` and a single-
 * letter `relationship` code. PrimaryKey is therefore NOT an account-level
 * identifier. To model one HubSpot record per physical account (with multiple
 * labeled owner associations), we collapse owner rows onto this stable key.
 *
 * PROVISIONAL (plan Phase 2 — pending Ivan / mapping-doc sign-off): the key is
 * branch + account type + last-4. Justin's worked DDA example identified the
 * physical account by (branch 104, type D, last4 3509). These three props
 * exist on all three account sources (DDA / Loans / CDs). If the mapping
 * document defines a fuller account number, change ACCOUNT_KEY_COLUMNS here —
 * it is the single source of truth for the grouping.
 *
 * Collision/over-merge guard: if any key component is missing on a row, we fall
 * back to `PK:<primary_key>` so the row stays its own singleton account rather
 * than being merged with other under-identified rows.
 */
const ACCOUNT_KEY_COLUMNS = ['branch_number', 'account_type', 'last_4_account_digits'];

function buildAccountKey(mappedRow) {
  const parts = ACCOUNT_KEY_COLUMNS.map(c => {
    const v = mappedRow[c];
    return v === null || v === undefined ? '' : String(v).trim();
  });
  if (parts.some(p => p === '')) {
    const pk = mappedRow.primary_key;
    return pk ? `PK:${String(pk).trim()}` : null;
  }
  return parts.join('|');
}

// The account sources that get owner-row collapse + a companion owner table
// feeding the association engine. (Debit Cards are excluded — they are one row
// per card and link to their single owner unlabeled.)
const ACCOUNT_SOURCES = {
  dda:   { staging: 'stg_deposits',      ownerStaging: 'stg_deposit_owners',      object: '2-60442978' },
  loans: { staging: 'stg_loans',         ownerStaging: 'stg_loan_owners',         object: '2-60442977' },
  cd:    { staging: 'stg_time_deposits', ownerStaging: 'stg_time_deposit_owners', object: '2-60442980' },
};

// Table name per source + destination HubSpot object ID.
const TABLES = {
  cif: {
    csvFile: 'HubSpot_CIF.csv',
    contactStaging: 'stg_contacts',
    companyStaging: 'stg_companies',
    contactObject: 'contacts',
    companyObject: 'companies',
    contactIdProperty: 'cif_number',
    companyIdProperty: 'cif_number',
    contactFields: CIF_CONTACT_FIELDS,
    companyFields: CIF_COMPANY_FIELDS,
  },
  dda: {
    csvFile: 'HubSpot_DDA.csv',
    staging: 'stg_deposits',
    ownerStaging: 'stg_deposit_owners',
    object: '2-60442978',
    idProperty: 'account_key',
    fields: DDA_FIELDS,
  },
  loans: {
    csvFile: 'HubSpot_Loan.csv',
    staging: 'stg_loans',
    ownerStaging: 'stg_loan_owners',
    object: '2-60442977',
    idProperty: 'account_key',
    fields: LOANS_FIELDS,
  },
  cd: {
    csvFile: 'HubSpot_CD.csv',
    staging: 'stg_time_deposits',
    ownerStaging: 'stg_time_deposit_owners',
    object: '2-60442980',
    idProperty: 'account_key',
    fields: CD_FIELDS,
  },
  debit_cards: {
    csvFile: 'HubSpot_Debit_Card.csv',
    staging: 'stg_debit_cards',
    object: '2-60442979',
    idProperty: 'composite_key',
    fields: DEBIT_CARDS_FIELDS,
  },
};

/**
 * Classify a raw CIF CSV row as 'contact', 'company', or 'unclassified'.
 * Matches the business rules from CLAUDE.md:
 *   - TaxIdType='T' AND FirstName empty AND LastName empty → company
 *   - TaxIdType='T' AND FirstName+LastName populated      → contact (biz contact)
 *   - TaxIdType is non-null AND != 'T'                    → contact
 *   - anything else (NULL taxidtype, partial name data)   → unclassified
 * Operates on the RAW CSV row (keys are CSV header names like 'TaxIdType').
 */
function classifyCifRow(row) {
  const taxId = row.TaxIdType;
  const first = (row.FirstName || '').trim();
  const last  = (row.LastName  || '').trim();

  if (taxId === 'T') {
    if (first === '' && last === '') return 'company';
    if (first !== '' && last !== '') return 'contact';
    return 'unclassified';
  }
  if (taxId && taxId !== 'T') return 'contact';
  return 'unclassified';
}

module.exports = {
  TABLES,
  CIF_COMMON,
  CIF_CONTACT_ONLY,
  CIF_COMPANY_ONLY,
  CIF_CONTACT_FIELDS,
  CIF_COMPANY_FIELDS,
  DDA_FIELDS,
  LOANS_FIELDS,
  CD_FIELDS,
  DEBIT_CARDS_FIELDS,
  ACCOUNT_KEY_COLUMNS,
  ACCOUNT_SOURCES,
  buildAccountKey,
  classifyCifRow,
};
